project:
  type: website

execute:
  echo: false
  warning: false
  message: false

website:
  title: "VisualMath"
  page-navigation: true
  bread-crumbs: true

  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

  sidebar:
    - title: "Root Finding"
      style: "docked"
      background: light
      contents:
        - href: root-finding/index.qmd
          text: Overview
        - href: root-finding/Bisection-Method/bisection.qmd
          text: Bisection Method
        - href: root-finding/Fixed-Point/fixed-point.qmd
          text: Fixed Point Iteration
        - href: root-finding/Newton/newton.qmd
          text: Newton's Method

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: mathjax