project:
  type: website

website:
  title: "Function Plotter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false
  message: false